### ISSUE TITLE
Support for freeform arrays (CR 20151015)

### ISSUE THREAD

**Issue by mtigas** [newsdev/archieml-ruby#4]
[October 15 candidate spec](http://archieml.org/spec/1.0/CR-20151015.html) added support for [freeform arrays](http://archieml.org/spec/1.0/CR-20151015.html#freeform-arrays), but Ruby gem doesn’t support it yet. (It _is_ in [archieml-js](https://github.com/newsdev/archieml-js), though. [diff](https://github.com/newsdev/archieml-js/pull/14/files))

**Comment by ashaw** [comment]
Test: 

```
test: freeform array
result: {"body": [{"type": "text","value": "abc"},{"type": "text","value": "def"}]}

[+body]
abc

def
[]
```

Result:

```
Failures:

  1) Archieml::Loader arrays_freeform_1.aml freeform array
     Failure/Error: aml.should == result

       expected: {"body"=>[{"type"=>"text", "value"=>"abc"}, {"type"=>"text", "value"=>"def"}]}
            got: {} (using ==)
       Diff:
       @@ -1,2 +1 @@
       -"body" => [{"type"=>"text", "value"=>"abc"}, {"type"=>"text", "value"=>"def"}],
     # ./spec/lib/archieml/loader_spec.rb:18:in `block (3 levels) in <top (required)>'
```

**Comment by abstrctn** [comment]
`v0.3.0` should now support freeforms - sorry for the delay!
